### ISSUE TITLE
Option for light developer theme

### ISSUE THREAD

**Issue by sefsh** [nt1m/devedition-theme-enabler#1]
An addon setting toggling between `light` and `dark` in setting `devtools.theme` would be useful I think.

**Comment by nt1m** [comment]
@yusf There is already a switch in the developer tools (Developer Tools > Options). Why create an extra one ?

**Comment by sefsh** [comment]
@nt1m Because this gives non developers easier access to this theme, which by the way is superior to Australis also to end-users. :grin:

**Comment by nt1m** [comment]
@yusf Sorry for the late reply, but adding a toggle will double the size of this 2 file (well 1, if you exclude the manifest) add-on, which I'm not sure is worth it. Most of the theme users are experienced enough to change the theme either using about:config or via devtools.

**Comment by nt1m** [comment]
The point of this add-on is also to be very lightweight.

**Comment by sefsh** [comment]
@nt1m Fair enough. Thank you for making this addon happen in the first place!
