### ISSUE TITLE
Migration path for Firefox 53 to compact themes

### ISSUE THREAD

**Issue by nt1m** [nt1m/devedition-theme-enabler#4]
If the Firefox version is 53 or higher, the add-on should enable the appropriate compact theme then should uninstall itself.

@bgrins, would you mind submitting a PR for this ?

**Comment by nt1m** [comment]
The add-on has more than 10 000 users, so I expect a migration path is important.

**Comment by bgrins** [comment]
If there's a way to mark as incompatible with >= 53, then the ui migration in nsBrowserGlue should be able to pick up the correct compact theme
